In [1]:
#Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np
# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None)

In [7]:
df_world_nulos=pd.read_csv("files/world_data_full_apply.csv",index_col=0)

df_world_nulos.head(5).T

,0,1,2,3,4
country,Afghanistan,Albania,Algeria,Andorra,Angola
density,60.0,105.0,18.0,164.0,26.0
abbreviation,AF,AL,DZ,AD,AO
agricultural_land,58.1,43.1,17.4,40.0,47.5
land_area,652.23,28.748,NaN,468.0,NaN
armed_forces_size,323.0,9.0,317.0,NaN,117.0
birth_rate,32.49,11.78,24.28,7.2,40.73
calling_code,93.0,355.0,213.0,376.0,244.0
capital/major_city,Kabul,Tirana,Algiers,Andorra la Vella,Luanda
co2-emissions,8.672,4.536,150.006,469.0,34.693
cpi,149.9,119.05,151.36,NaN,261.73
cpi_change,2.3,1.4,2.0,NaN,17.1
currency-code,AFN,ALL,DZD,EUR,AOA
fertility_rate,4.47,1.62,3.02,1.27,5.52
forested_area,2.1,28.1,0.8,34.0,46.3
gasoline_price,0.7,1.36,0.28,1.51,0.97
gdp,19101353833.0,15278077447.0,169988236398.0,3154057987.0,94635415870.0
gross_primary_education_enrollment,104.0,107.0,109.9,106.4,113.5
gross_tertiary_education_enrollment,9.7,55.0,51.4,NaN,9.3
infant_mortality,47.9,7.8,20.1,2.7,51.6
largest_city,Kabul,Tirana,Algiers,Andorra la Vella,Luanda
life_expectancy,64.5,78.5,76.7,NaN,60.8
maternal_mortality_ratio,638.0,15.0,112.0,NaN,241.0
minimum_wage,0.43,1.12,0.95,6.63,0.71
official_language,Pashto,Albanian,Arabic,Catalan,Portuguese
out_of_pocket_health_expenditure,78.4,56.9,28.1,36.4,33.4
physicians_per_thousand,0.28,1.2,1.72,3.33,0.21
population,NaN,NaN,NaN,77.142,NaN
population_labor_force_participation,48.9,55.7,41.2,NaN,77.5
tax_revenue,9.3,18.6,37.2,NaN,9.2
total_tax_rate,71.4,36.6,66.1,NaN,49.1
unemployment_rate,11.12,12.33,11.7,NaN,6.89
urban_population,NaN,NaN,NaN,67.873,NaN
latitude,33.93911,41.153332,28.033886,42.506285,-11.202692
longitude,67.709953,20.168331,1.659626,1.521801,17.873887
continent,Asia,Europe,Africa,Europe,Africa

In [ ]:
#1)Identificación de Valores Nulos: Identifica todas las columnas que contengan valores nulos en el DataFrame

(round(df_world_nulos.isna().sum()/df_world_nulos.shape[0]*100),2)

#Hemos detectado un porcentaje muy eevado en variables como population,urban population,minimum wage.aRMED FORCES SIZE, BIRTH RATE y tax revenue , tienen porcentajes de nulos altos también pero no tanpreocupantes.

(country                                  0.0
 density                                  0.0
 abbreviation                             4.0
 agricultural_land                        4.0
 land_area                               15.0
 armed_forces_size                       15.0
 birth_rate                               3.0
 calling_code                             1.0
 capital/major_city                       2.0
 co2-emissions                            6.0
 cpi                                     10.0
 cpi_change                               8.0
 currency-code                            8.0
 fertility_rate                           4.0
 forested_area                            4.0
 gasoline_price                          10.0
 gdp                                      1.0
 gross_primary_education_enrollment       4.0
 gross_tertiary_education_enrollment      6.0
 infant_mortality                         3.0
 largest_city                             3.0
 life_expectancy                          4.0
 maternal_mortality_ratio                 7.0
 minimum_wage                            23.0
 official_language                        3.0
 out_of_pocket_health_expenditure         4.0
 physicians_per_thousand                  4.0
 population                              80.0
 population_labor_force_participation    10.0
 tax_revenue                             13.0
 total_tax_rate                           6.0
 unemployment_rate                       10.0
 urban_population                        77.0
 latitude                                 1.0
 longitude                                1.0
 continent                                1.0
 dtype: float64,
 2)

In [10]:
#2)Selección de Método de Imputación: Discute en tu compañera cuál sería la mejor estrategia para manejar los valores nulos en cada una de las columnas identificadas en el paso anterior.

df_world_nulos["population"].value_counts(dropna=False)

population
NaN        156
77.142       1
97.118       1
389.482      1
287.025      1
390.353      1
727.145      1
433.285      1
483.628      1
850.886      1
973.560      1
71.808       1
889.953      1
112.003      1
782.766      1
836.000      1
361.313      1
117.606      1
38.019       1
645.397      1
530.953      1
502.653      1
58.791       1
113.815      1
38.964       1
622.137      1
10.084       1
18.233       1
52.823       1
182.790      1
100.455      1
202.506      1
33.860       1
215.056      1
97.625       1
669.823      1
581.372      1
100.209      1
11.646       1
299.882      1
Name: count, dtype: int64

In [13]:
filtro_nPopulation=df_world_nulos["population"].isna()
filtro_nPopulation

0       True
1       True
2       True
3      False
4       True
       ...
190     True
191     True
192     True
193     True
194     True
Name: population, Length: 195, dtype: bool

In [14]:
df_world_nulos.loc[filtro_nPopulation,"country"]

0      Afghanistan
1          Albania
2          Algeria
4           Angola
6        Argentina
          ...
190      Venezuela
191        Vietnam
192          Yemen
193         Zambia
194       Zimbabwe
Name: country, Length: 156, dtype: str

In [ ]:
#Luego de analizar los datos, decidimos que population y urban population no se hará imputación de nulos debido al alto porcentaje de nulos.
#Nos quedan las siguientes variables para ver que hacemos con los nulos:minimum wage.aRMED FORCES SIZE, BIRTH RATE y tax revenue , tienen porcentajes

In [15]:
df_world_nulos["minimum_wage"].value_counts(dropna=False)

minimum_wage
NaN      45
2.00      3
0.41      3
1.12      2
0.95      2
         ..
10.13     1
7.25      1
1.66      1
1.56      1
0.73      1
Name: count, Length: 115, dtype: int64

In [26]:
round(df_world_nulos.describe().reset_index(),2).T

,0,1,2,3,4,5,6,7
index,count,mean,std,min,25%,50%,75%,max
density,195.0,134.5,157.31,1.26,26.17,83.0,165.5,847.0
agricultural_land,188.0,39.12,21.78,0.6,21.7,39.6,55.38,82.6
land_area,165.0,255.21,258.39,0.0,41.28,148.46,430.0,964.0
armed_forces_size,166.0,103.78,167.16,0.0,10.25,28.5,128.25,936.0
birth_rate,189.0,20.21,9.95,5.9,11.3,17.95,28.75,46.08
calling_code,194.0,360.55,323.24,1.0,82.5,255.5,506.75,1876.0
co2-emissions,183.0,125.92,181.79,1.02,7.6,34.48,185.03,727.97
cpi,175.0,144.19,54.78,99.03,113.67,124.74,155.93,550.93
cpi_change,179.0,6.72,24.45,-4.3,1.0,2.3,4.25,254.9
fertility_rate,188.0,2.7,1.28,0.98,1.7,2.24,3.6,6.91
forested_area,188.0,32.02,23.79,0.0,11.0,32.0,48.18,98.3
gasoline_price,175.0,1.0,0.37,0.0,0.76,0.98,1.24,2.0
gdp,193.0,477295901399.539978,2172173359474.050049,47271463.0,8454619608.0,34387229486.0,234094042939.0,21427700000000.0
gross_primary_education_enrollment,188.0,102.47,13.15,23.4,98.95,102.55,108.02,142.5
gross_tertiary_education_enrollment,183.0,37.96,29.26,0.8,12.15,31.2,63.15,136.6
infant_mortality,189.0,21.33,19.55,1.4,6.0,14.0,32.7,84.5
life_expectancy,187.0,72.28,7.48,52.8,67.0,73.2,77.5,85.4
maternal_mortality_ratio,181.0,160.39,233.5,2.0,13.0,53.0,186.0,1150.0
minimum_wage,150.0,2.19,2.97,0.01,0.4,1.04,2.45,13.59
out_of_pocket_health_expenditure,188.0,32.64,19.17,0.2,17.45,30.7,43.98,81.6
physicians_per_thousand,188.0,1.84,1.68,0.01,0.33,1.46,2.94,8.42
population,39.0,333.54,296.47,10.08,87.13,215.06,556.16,973.56
population_labor_force_participation,176.0,62.74,10.5,38.0,56.15,62.45,69.5,86.8
tax_revenue,169.0,16.57,6.96,0.0,11.7,16.3,21.1,37.2
total_tax_rate,183.0,40.82,20.56,8.0,30.6,37.2,48.0,219.6
unemployment_rate,176.0,6.89,5.08,0.09,3.4,5.36,9.49,28.18
urban_population,45.0,279.46,283.32,5.46,40.76,179.04,417.76,984.81
latitude,194.0,19.09,23.96,-40.9,4.54,17.27,40.12,64.96
longitude,194.0,20.23,66.72,-175.2,-7.94,20.97,48.28,178.07

In [ ]:
#Consideramos que un método apropiado para analizar los nulos de la variable salario mínimo, podría ser interesante el método de los vecinos.

imputer_knn = KNNImputer(n_neighbors= 1)#Definimos la variable y le indicamos el número de vecinos a visitar

In [33]:
df_world_nulos["minimum_wage_2"] = imputer_knn.fit_transform(df_world_nulos[["tax_revenue"]])
df_world_nulos.sample(10)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent,minimum_wage_2
127,North Korea,214.0,KP,21.8,120.538,NaN,13.89,850.0,Pyongyang,28.284,NaN,NaN,KPW,1.90,40.7,0.58,3.210000e+10,112.8,27.0,13.7,Pyongyang,72.1,89.0,NaN,Korean,NaN,3.67,NaN,80.4,NaN,NaN,2.74,NaN,40.339852,127.510093,Asia,16.573964
190,Venezuela,32.0,VE,24.5,912.050,343.0,17.88,58.0,Caracas,164.175,NaN,254.9,VED,2.27,52.7,0.00,4.823593e+11,97.2,79.3,21.4,Caracas,72.1,125.0,0.01,Spanish,45.8,1.92,NaN,59.7,NaN,73.3,8.80,NaN,6.423750,-66.589730,South America,16.573964
98,Liechtenstein,238.0,LI,32.2,160.000,NaN,9.90,423.0,Vaduz,51.000,NaN,NaN,CHF,1.44,43.1,1.74,6.552859e+09,104.7,35.6,NaN,Schaan,83.0,NaN,NaN,German,NaN,NaN,38.019,NaN,NaN,21.6,NaN,5.464,47.141039,9.520935,Europe,16.573964
59,Finland,18.0,FI,7.5,338.145,25.0,8.60,358.0,Helsinki,45.871,112.33,1.0,EUR,1.41,73.1,1.45,2.687612e+11,100.2,88.2,1.4,Helsinki,81.7,3.0,NaN,Swedish,19.9,3.81,NaN,59.1,20.8,36.6,6.59,NaN,61.924110,25.748151,Europe,20.800000
91,Kyrgyzstan,34.0,KG,55.0,199.951,21.0,27.10,996.0,Bishkek,9.787,155.68,1.1,KGS,3.30,3.3,0.56,8.454620e+09,107.6,41.3,16.9,Bishkek,71.4,60.0,0.09,Russian,48.2,1.88,NaN,59.8,18.0,29.0,6.33,NaN,41.204380,74.766098,Asia,18.000000
194,Zimbabwe,38.0,ZW,41.9,390.757,51.0,30.68,263.0,Harare,10.983,105.51,0.9,NaN,3.62,35.5,1.34,2.144076e+10,109.9,10.0,33.9,Harare,61.2,458.0,NaN,Shona,25.8,0.21,NaN,83.1,20.7,31.6,4.95,NaN,-19.015438,29.154857,Africa,20.700000
51,Egypt,103.0,EG,3.8,NaN,836.0,26.38,20.0,Cairo,238.560,288.57,9.2,EGP,3.33,0.1,0.40,3.031751e+11,106.3,35.2,18.1,Cairo,71.8,37.0,NaN,Modern Standard Arabic,62.0,0.45,NaN,46.4,12.5,44.4,10.76,NaN,26.820553,30.802498,Africa,12.500000
191,Vietnam,314.0,VN,39.3,331.210,522.0,16.75,84.0,Hanoi,192.668,163.52,2.8,VND,2.05,48.1,0.80,2.619212e+11,110.6,28.5,16.5,Ho Chi Minh City,75.3,43.0,0.73,Vietnamese,43.5,0.82,NaN,77.4,19.1,37.6,2.01,NaN,14.058324,108.277199,Asia,19.100000
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa,37.200000
92,Laos,32.0,LA,10.3,236.800,129.0,23.55,856.0,Vientiane,17.763,135.87,3.3,LAK,2.67,82.1,0.93,1.817384e+10,102.4,15.0,37.6,Vientiane,67.6,185.0,0.83,Lao,45.4,0.37,NaN,78.5,12.9,24.1,0.63,NaN,19.856270,102.495496,Asia,12.900000

In [ ]:
df_world_nulos["minimum_wage_2"] = imputer_knn.fit_transform(df_world_nulos[["tax_revenue","total_tax_rate","gross_primary_education_enrollment","gross_tertiary_education_enrollment"]])